/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.conf;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class addedittransac extends javax.swing.JFrame {

  private boolean isEditMode = false;
    private int edit_trans_id = -1;
    
    public addedittransac() {
    initComponents();
    setTitle("Add Transaction");
    booklabel.setText("SAVE");
    borrowdate.setText(java.time.LocalDate.now()
        .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd")));
}
    

    

public void setAddMode() {
    isEditMode = false;
    edit_trans_id = -1;
    clearAllFields();
    setTitle("Add Transaction");
    booklabel.setText("SAVE");
    // bookid1 = trans_id display field
    bookid1.setText("(auto)");
    bookid1.setEditable(false);
    bookid1.setBackground(new java.awt.Color(200, 200, 200));
    borrowdate.setText(java.time.LocalDate.now()
        .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd")));
}

public void setEditMode(int tid, String uid, String uname,
                        String bid, String btitle,
                        String bdate, String rdate, String stat) {
    isEditMode = true;
    edit_trans_id = tid;

    bookid1.setText(String.valueOf(tid));   // trans_id display
    bookid1.setEditable(false);
    bookid1.setBackground(new java.awt.Color(200, 200, 200));

    // ✅ Map to actual UI variable names from initComponents
    userid.setText(uid);          // user_id
    username.setText(uname);      // user_name
    bookid.setText(bid);          // book_id
    title.setText(btitle);        // book_title
    borrowdate.setText(bdate);    // borrow_date
    borrowdate1.setText(rdate);   // return_date

    jComboBox1.setSelectedItem(stat != null ? stat.trim() : "Borrowed");

    setTitle("Edit Transaction – ID: " + tid);
    booklabel.setText("UPDATE");    
}

    private void clearAllFields() {
        bookid1.setText("");      // trans_id
    userid.setText("");       // user_id
    username.setText("");     // user_name
    bookid.setText("");       // book_id
    title.setText("");        // book_title
    borrowdate.setText("");   // borrow_date
    borrowdate1.setText("");  // return_date
    jComboBox1.setSelectedIndex(0);
}


    /**
     * Creates new form AddEditUser
     */
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JPanel();
        booklabel = new javax.swing.JLabel();
        trans_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        bookid1 = new javax.swing.JTextField();
        userid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        borrowdate = new javax.swing.JTextField();
        borrowdate1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSACTION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 60));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setText("Book ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel4.setText("Transaction ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel5.setText("User ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, 30));

        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });
        jPanel1.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, 30));

        status.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        status.setText("Status:");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 60, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Borrowed", "Returned" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 130, 30));

        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });
        confirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booklabel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        booklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklabel.setText("Confirm");
        confirm.add(booklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        jPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 40));
        jPanel1.add(trans_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setText("Title:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 60, 30));

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 130, 30));

        bookid1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookid1ActionPerformed(evt);
            }
        });
        jPanel1.add(bookid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, 30));
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setText("Username:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setText("Borrow Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 80, 30));

        borrowdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowdateActionPerformed(evt);
            }
        });
        jPanel1.add(borrowdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 130, 30));

        borrowdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(borrowdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 130, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel9.setText("Return Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
          if (userid.getText().trim().isEmpty() ||
        bookid.getText().trim().isEmpty() ||
        borrowdate.getText().trim().isEmpty() ||
        borrowdate1.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
            "Please fill in User ID, Book ID, Borrow Date, and Return Date.",
            "Required Fields", JOptionPane.WARNING_MESSAGE);
        return;
    }

   conf con = new conf();
    String sql;
    boolean success;

    // ✅ Read from actual UI variables
    String uidVal    = userid.getText().trim();
    String unameVal  = username.getText().trim();
    String bidVal    = bookid.getText().trim();
    String btitleVal = title.getText().trim();
    String bdateVal  = borrowdate.getText().trim();
    String rdateVal  = borrowdate1.getText().trim();
    String statusVal = jComboBox1.getSelectedItem().toString();

    if (isEditMode) {
    sql = "UPDATE tbl_transaction SET "
        + "a_id=?, user_name=?, bok_id=?, title=?, "   // ✅ bok_id, title
        + "borrow_date=?, return_date=?, status=? "
        + "WHERE trans_id=?";
    success = con.executeUpdate(sql,
        uidVal, unameVal, bidVal, btitleVal,
        bdateVal, rdateVal, statusVal,
        edit_trans_id);
} else {
    sql = "INSERT INTO tbl_transaction "
        + "(a_id, user_name, bok_id, title, borrow_date, return_date, status) "  // ✅ bok_id, title
        + "VALUES (?, ?, ?, ?, ?, ?, ?)";
    success = con.executeUpdate(sql,
        uidVal, unameVal, bidVal, btitleVal,
        bdateVal, rdateVal, statusVal);
}

    if (success) {
        JOptionPane.showMessageDialog(this,
            isEditMode ? "Transaction updated!" : "Transaction saved!",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        clearAllFields();
        dispose();
    } else {
        JOptionPane.showMessageDialog(this,
            "Operation failed. Please try again.",
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_confirmMouseClicked

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void bookid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookid1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void borrowdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowdateActionPerformed

    private void borrowdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowdate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addedittransac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookid1;
    private javax.swing.JLabel booklabel;
    private javax.swing.JTextField borrowdate;
    private javax.swing.JTextField borrowdate1;
    private javax.swing.JPanel confirm;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel status;
    private javax.swing.JTextField title;
    private javax.swing.JLabel trans_id;
    private javax.swing.JTextField userid;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    
}
