/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.conf;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class addedittransac extends javax.swing.JFrame {

  private boolean isEditMode = false;
    private int edit_trans_id = -1;
    
    public addeditransaction() {
        initComponents();
        setTitle("Add Transaction");
        trans_label.setText("SAVE");
        // Set today as default borrow date
        borrow_date.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
        loadUsersDropdown();
        loadBooksDropdown();
    }
    private void loadUsersDropdown() {
        conf con = new conf();
        java.sql.Connection conn = conf.connectDB();
        try {
            java.sql.PreparedStatement ps = conn.prepareStatement(
                "SELECT a_id, name FROM tbl_acc WHERE status = 'Active'");
            java.sql.ResultSet rs = ps.executeQuery();
            user_combo.removeAllItems();
            user_combo.addItem("-- Select User --");
            while (rs.next()) {
                user_combo.addItem(rs.getInt("a_id") + " - " + rs.getString("name"));
            }
        } catch (Exception e) {
            System.out.println("Error loading users: " + e.getMessage());
        }
    }
    private void loadBooksDropdown() {
        java.sql.Connection conn = conf.connectDB();
        try {
            java.sql.PreparedStatement ps = conn.prepareStatement(
                "SELECT bok_id, title FROM tbl_books WHERE status = 'Available'");
            java.sql.ResultSet rs = ps.executeQuery();
            book_combo.removeAllItems();
            book_combo.addItem("-- Select Book --");
            while (rs.next()) {
                book_combo.addItem(rs.getInt("bok_id") + " - " + rs.getString("title"));
            }
        } catch (Exception e) {
            System.out.println("Error loading books: " + e.getMessage());
        }
    }

    

public void setAddMode() {
    isEditMode = false;
        edit_trans_id = -1;
        clearAllFields();
        setTitle("Add Transaction");
        trans_label.setText("SAVE");
        trans_id_field.setText("(auto)");
        trans_id_field.setEditable(false);
        trans_id_field.setBackground(new java.awt.Color(200, 200, 200));
        borrow_date.setText(LocalDate.now()
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
}

public void setEditMode(int bok_id,String ttl, String auth, String gen, 
                        String qty, String stat) {
  isEditMode = true;
        edit_trans_id = trans_id;

        trans_id_field.setText(String.valueOf(trans_id));
        trans_id_field.setEditable(false);
        trans_id_field.setBackground(new java.awt.Color(200, 200, 200));

        // Set manual fields
        user_id_field.setText(uid);
        book_id_field.setText(bid);
        borrow_date.setText(bdate);
        return_date.setText(rdate);

        // Set status combo
        status_combo.setSelectedItem(stat != null ? stat.trim() : "Borrowed");

        setTitle("Edit Transaction – ID: " + trans_id);
        trans_label.setText("UPDATE");
    }

    private void clearAllFields() {
        trans_id_field.setText("");
        user_id_field.setText("");
        book_id_field.setText("");
        borrow_date.setText("");
        return_date.setText("");
        status_combo.setSelectedIndex(0);
        user_combo.setSelectedIndex(0);
        book_combo.setSelectedIndex(0);
}

private void clearAllFields() {
     bookid1.setText("");
    userid.setText("");      // ✅ using title JTextField now
    author.setText("");
    genre.setText("");
    quantity.setText("");
    jComboBox1.setSelectedIndex(0);
    trans_id.setText("");
}
    /**
     * Creates new form AddEditUser
     */
    public addedittransac() {
        initComponents();
    setTitle("Add New Book");
    booklabel.setText("SAVE");
    // ✅ Removed ButtonGroup for male/female — not needed for books
  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        book_label = new javax.swing.JPanel();
        booklabel = new javax.swing.JLabel();
        trans_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        bookid1 = new javax.swing.JTextField();
        userid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setText("Book ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 60, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel4.setText("Transaction ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));

        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel5.setText("User ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, 30));

        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });
        jPanel1.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, 30));

        status.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        status.setText("Status:");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 60, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Out of Stock" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 130, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IMAGE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 150, 108));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 170, 130));

        book_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                book_labelMouseClicked(evt);
            }
        });
        book_label.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booklabel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        booklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklabel.setText("LABEL");
        book_label.add(booklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 130, -1));

        jPanel1.add(book_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 130, 40));
        jPanel1.add(trans_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setText("Title:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 60, 30));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 130, 30));

        bookid1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookid1ActionPerformed(evt);
            }
        });
        jPanel1.add(bookid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, 30));
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setText("Username:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void book_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_labelMouseClicked
         if (userid.getText().trim().isEmpty() ||
        author.getText().trim().isEmpty() ||
        quantity.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
            "Please fill in Title, Author, and Quantity.",
            "Required Fields", JOptionPane.WARNING_MESSAGE);
        return;
    }

    conf con = new conf();
    String sql;
    boolean success;

    String titleVal    = userid.getText().trim();     // ✅ title JTextField
    String authorVal   = author.getText().trim();
    String genreVal    = genre.getText().trim();
    String quantityVal = quantity.getText().trim();
    String statusVal   = jComboBox1.getSelectedItem().toString();

    if (isEditMode) {
        sql = "UPDATE tbl_books SET "
            + "title=?, author=?, genre=?, quantity=?, status=? "
            + "WHERE bok_id=?";
        success = con.executeUpdate(sql,
            titleVal, authorVal, genreVal, quantityVal, statusVal,
            edit_bok_id);
    } else {
        sql = "INSERT INTO tbl_books (title, author, genre, quantity, status) "
            + "VALUES (?, ?, ?, ?, ?)";
        success = con.executeUpdate(sql,
            titleVal, authorVal, genreVal, quantityVal, statusVal);
    }

    if (success) {
        JOptionPane.showMessageDialog(this,
            isEditMode ? "Book updated successfully!" : "Book added successfully!",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        clearAllFields();
        dispose();
    } else {
        JOptionPane.showMessageDialog(this,
            "Operation failed. Please try again.",
            "Error", JOptionPane.ERROR_MESSAGE);
    
    }
    }//GEN-LAST:event_book_labelMouseClicked

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void bookid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookid1ActionPerformed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addedittransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addedittransac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JPanel book_label;
    private javax.swing.JTextField bookid1;
    private javax.swing.JLabel booklabel;
    private javax.swing.JTextField genre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel status;
    private javax.swing.JLabel trans_id;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables

    
}
