/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.conf;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddEditUser extends javax.swing.JFrame {

    private String selectedGender;
    private boolean isEditMode = false;
private int edit_a_id = -1;     // we will store the real database primary key (a_id)

public void setAddMode() {
    isEditMode = false;
    edit_a_id = -1;
    clearAllFields();
    setTitle("Add New User");
    user_label.setText("SAVE");
    // No userid anymore
}

public void setEditMode(int a_id, String uid, String uname, String em, 
                        String gender, String stat, String addr) {
    isEditMode = true;
    edit_a_id = a_id;

    username.setText(uname);       // name → username field
    email.setText(em);

    if ("Male".equalsIgnoreCase(gender)) {
        male.doClick();
    } else if ("Female".equalsIgnoreCase(gender)) {
        female.doClick();
    }

    jComboBox1.setSelectedItem(gender);
    jTextArea1.setText(addr);

    setTitle("Edit User");
    user_label.setText("UPDATE");
}

private void clearAllFields() {
    userid.setText("");
    username.setText("");
    email.setText("");
    male.setSelected(false);
    female.setSelected(false);
    selectedGender = "";
    jComboBox1.setSelectedIndex(0);
    jTextArea1.setText("");
}
    /**
     * Creates new form AddEditUser
     */
    public AddEditUser() {
        initComponents();
        setTitle("Add New User");
user_label.setText("SAVE");
        ButtonGroup bg = new ButtonGroup();
    bg.add(male);
    bg.add(female);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userlabel = new javax.swing.JPanel();
        user_label = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 30));

        userid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel4.setText("User ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 30));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, 30));

        genderLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        genderLabel.setText("Gender:");
        jPanel1.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 30));

        status.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        status.setText("Status:");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Lonely" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 130, 30));

        address.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        address.setText("Address:");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 60, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 170, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IMAGE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 150, 108));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 170, 130));

        userlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userlabelMouseClicked(evt);
            }
        });
        userlabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_label.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        user_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_label.setText("LABEL");
        userlabel.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 120, -1));

        jPanel1.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 120, 40));

        male.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 70, 30));

        female.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 70, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void userlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userlabelMouseClicked
        if (username.getText().trim().isEmpty() ||
        email.getText().trim().isEmpty() ||
        selectedGender.isEmpty()) {
        
        JOptionPane.showMessageDialog(this,
            "Please fill Username, Email, Gender",
            "Required", JOptionPane.WARNING_MESSAGE);
        return;
    }

    conf con = new conf();
    boolean success;
    String sql;

    String nameVal    = username.getText().trim();
    String emailVal   = email.getText().trim();
    String genderVal  = selectedGender;
    String typeVal    = jComboBox1.getSelectedItem().toString();
    String addressVal = jTextArea1.getText().trim();
    String statusVal  = "Active";  // or add a field for this

    if (isEditMode) {
        sql = "UPDATE tbl_acc SET "
            + "name = ?, email = ?, gender = ?, type = ?, address = ?, status = ? "
            + "WHERE a_id = ?";

        success = con.executeUpdate(sql,
            nameVal, emailVal, genderVal, typeVal, addressVal, statusVal,
            edit_a_id
        );
    } else {
        sql = "INSERT INTO tbl_acc "
            + "(name, email, gender, type, address, status) "
            + "VALUES (?, ?, ?, ?, ?, ?)";

        success = con.executeUpdate(sql,
            nameVal, emailVal, genderVal, typeVal, addressVal, statusVal
        );
    }

    if (success) {
        JOptionPane.showMessageDialog(this,
            isEditMode ? "User updated!" : "User added!",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        if (!isEditMode) clearAllFields();
        dispose();  // optional
    } else {
        JOptionPane.showMessageDialog(this, "Operation failed.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    sql = "INSERT INTO tbl_acc (name, email, gender, type, status, address) VALUES (?, ?, ?, ?, ?, ?)";
success = con.executeUpdate(sql,
    username.getText().trim(),
    email.getText().trim(),
    selectedGender,
    jComboBox1.getSelectedItem().toString(),
    "Active",
    jTextArea1.getText().trim()
);

// UPDATE (Edit)
sql = "UPDATE tbl_acc SET name = ?, email = ?, gender = ?, type = ?, status = ?, address = ? WHERE a_id = ?";
success = con.executeUpdate(sql,
    username.getText().trim(),
    email.getText().trim(),
    selectedGender,
    jComboBox1.getSelectedItem().toString(),
    "Active",
    jTextArea1.getText().trim(),
    edit_a_id
);
    }//GEN-LAST:event_userlabelMouseClicked

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
         selectedGender = "Male";
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        selectedGender = "Female";
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField email;
    public javax.swing.JRadioButton female;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JRadioButton male;
    private javax.swing.JLabel status;
    private javax.swing.JLabel user_label;
    private javax.swing.JTextField userid;
    private javax.swing.JPanel userlabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    void setEditMode(int a_id, String nam, String em, String gen, String typ, String adr) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
