/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.conf;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER34
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form books
     */
    public transaction() {
        initComponents();
        displayTransactions();
        // Search column combo
    searchColumn = new javax.swing.JComboBox<>(new String[]{
    "trans_id", "a_id", "user_name", "bok_id", "title",  // ✅ bok_id, title
    "borrow_date", "return_date", "status"
});
        searchColumn.setBackground(new java.awt.Color(0, 153, 0));
        searchColumn.setForeground(java.awt.Color.WHITE);
        searchColumn.setFont(new java.awt.Font("Arial Black", 0, 10));
        jPanel1.add(searchColumn,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 120, 40));

        search.addActionListener(e -> searchTransactions());

        searchfilter.getDocument().addDocumentListener(
            new javax.swing.event.DocumentListener() {
                public void insertUpdate(javax.swing.event.DocumentEvent e) { }
                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    if (searchfilter.getText().trim().isEmpty()) displayTransactions();
                }
                public void changedUpdate(javax.swing.event.DocumentEvent e) { }
            });
    }
    private javax.swing.JComboBox<String> searchColumn;
   
    void displayTransactions() {
    conf con = new conf();
    con.displayData("SELECT * FROM tbl_transaction", usertable); // ✅ usertable not transtable
}
    private void searchTransactions() {
    String keyword = searchfilter.getText().trim();
    String column  = searchColumn.getSelectedItem().toString();
    conf con = new conf();

    if (keyword.isEmpty()) { displayTransactions(); return; }

    String sql;
    if (column.equals("trans_id")) {
        sql = "SELECT * FROM tbl_transaction WHERE CAST(trans_id AS TEXT) LIKE ?";
    } else {
        sql = "SELECT * FROM tbl_transaction WHERE " + column + " LIKE ?";
    }
    con.displayData(sql, usertable, "%" + keyword + "%"); // ✅ usertable
}

     Color navcolor = new Color (0,153,0);
    Color headercolor = new Color (0,204,0);
    Color bodycolor = new Color (0,255,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        searchfilter = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        navbar = new javax.swing.JPanel();
        dashpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        userstable = new javax.swing.JLabel();
        bookspanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        transactionpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(0, 153, 0));
        search.setText("SEARCH");
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 90, 40));

        add.setBackground(new java.awt.Color(0, 153, 0));
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        edit.setBackground(new java.awt.Color(0, 153, 0));
        edit.setText("EDIT");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 40));
        jPanel1.add(searchfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 200, 40));

        delete.setBackground(new java.awt.Color(0, 153, 0));
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 40));

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(usertable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 600, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 420));

        navbar.setBackground(new java.awt.Color(0, 153, 0));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashpanel.setBackground(new java.awt.Color(0, 153, 0));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpanelMouseExited(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        dashpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 50));

        userpanel.setBackground(new java.awt.Color(0, 153, 0));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpanelMouseExited(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userstable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        userstable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userstable.setText("USER");
        userpanel.add(userstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 50));

        bookspanel.setBackground(new java.awt.Color(0, 153, 0));
        bookspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookspanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookspanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookspanelMouseExited(evt);
            }
        });
        bookspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BOOKS");
        bookspanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(bookspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 50));

        transactionpanel.setBackground(new java.awt.Color(0, 153, 0));
        transactionpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionpanelMouseExited(evt);
            }
        });
        transactionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BORROW TRANSACTION");
        transactionpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(transactionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 50));

        account.setBackground(new java.awt.Color(0, 153, 0));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACCOUNT");
        account.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 40));

        navbar.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 60));

        getContentPane().add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       addedittransac form = new addedittransac(); // ✅ correct class name
    form.setAddMode();
    form.setVisible(true);
    form.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            displayTransactions();
        }
    });
    }//GEN-LAST:event_addActionPerformed

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       int row = usertable.getSelectedRow(); // ✅ usertable
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a transaction to edit.",
            "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }
    try {
        int    trans_id    = Integer.parseInt(safeGet(row, 0));  // trans_id
String a_id        = safeGet(row, 1);                    // a_id
String user_name   = safeGet(row, 2);                    // user_name
String bok_id      = safeGet(row, 3);                    // bok_id
String title       = safeGet(row, 4);                    // title
String borrow_date = safeGet(row, 5);                    // borrow_date
String return_date = safeGet(row, 6);                    // return_date
String status      = safeGet(row, 7);                    // status

addedittransac form = new addedittransac();
form.setEditMode(trans_id, a_id, user_name, bok_id, title, borrow_date, return_date, status);
        form.setVisible(true);
        form.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                displayTransactions();
            }
        });
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
            "Edit Error", JOptionPane.ERROR_MESSAGE);
    }
        }

        // Safe helper
      private String safeGet(int row, int col) {
            Object val = usertable.getValueAt(row, col);
    return val != null ? val.toString().trim() : "";
    }//GEN-LAST:event_editActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       int row = usertable.getSelectedRow(); // ✅ usertable
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a transaction to delete.",
            "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int trans_id = Integer.parseInt(safeGet(row, 0));
    String borrower = safeGet(row, 2);

    int choice = JOptionPane.showConfirmDialog(this,
        "Delete transaction for: " + borrower + " ?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (choice == JOptionPane.YES_OPTION) {
        conf con = new conf();
        boolean ok = con.executeUpdate(
            "DELETE FROM tbl_transaction WHERE trans_id = ?", trans_id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Transaction deleted.", "Success",
                JOptionPane.INFORMATION_MESSAGE);
            displayTransactions();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete.", "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    }//GEN-LAST:event_deleteActionPerformed

    private void dashpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseEntered
        dashpanel.setBackground(bodycolor);
    }//GEN-LAST:event_dashpanelMouseEntered

    private void dashpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseExited
        dashpanel.setBackground(navcolor);
    }//GEN-LAST:event_dashpanelMouseExited

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
        userstable us = new userstable();
        us.setVisible(true);
    }//GEN-LAST:event_userpanelMouseClicked

    private void userpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseEntered
        userpanel.setBackground(bodycolor);
    }//GEN-LAST:event_userpanelMouseEntered

    private void userpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseExited
        userpanel.setBackground(navcolor);
    }//GEN-LAST:event_userpanelMouseExited

    private void bookspanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseEntered
        bookspanel.setBackground(bodycolor);
    }//GEN-LAST:event_bookspanelMouseEntered

    private void bookspanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseExited
        bookspanel.setBackground(navcolor);
    }//GEN-LAST:event_bookspanelMouseExited

    private void transactionpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionpanelMouseEntered
        transactionpanel.setBackground(bodycolor);
    }//GEN-LAST:event_transactionpanelMouseEntered

    private void transactionpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionpanelMouseExited
        transactionpanel.setBackground(navcolor);
    }//GEN-LAST:event_transactionpanelMouseExited

    private void bookspanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseClicked
       books boks = new books();
       boks.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bookspanelMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        userForm user = new userForm();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        account.setBackground(bodycolor);
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(navcolor);
    }//GEN-LAST:event_accountMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JButton add;
    private javax.swing.JPanel bookspanel;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navbar;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchfilter;
    private javax.swing.JPanel transactionpanel;
    private javax.swing.JPanel userpanel;
    private javax.swing.JLabel userstable;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
