/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import java.awt.Color;

/**
 *
 * @author USER34
 */
public class userdashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public userdashboard() {
        initComponents();
       loadUserDashboardStats();
    }
    private void loadUserDashboardStats() {
    try {
        int a_id = config.session.getInstance().getA_id();
        String name = config.session.getInstance().getUsername();

        java.sql.Connection conn = config.conf.connectDB();

        // Stats for THIS user only
        int myTransactions = getCount(conn,
            "SELECT COUNT(*) FROM tbl_transaction WHERE a_id = " + a_id);
        int myBorrowed = getCount(conn,
            "SELECT COUNT(*) FROM tbl_transaction WHERE a_id = " + a_id + " AND status='Borrowed'");
        int myReturned = getCount(conn,
            "SELECT COUNT(*) FROM tbl_transaction WHERE a_id = " + a_id + " AND status='Returned'");
        int totalBooks = getCount(conn,
            "SELECT COUNT(*) FROM tbl_books");
        int availableBooks = getCount(conn,
            "SELECT COUNT(*) FROM tbl_books WHERE status='Available'");

        conn.close();

        // ✅ Welcome label
        javax.swing.JLabel welcomeLabel = new javax.swing.JLabel(
            "Welcome, " + name + "!", javax.swing.SwingConstants.CENTER);
        welcomeLabel.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 16));
        welcomeLabel.setForeground(new java.awt.Color(0, 102, 0));
        welcomeLabel.setBounds(10, 10, 600, 35);
        jPanel1.add(welcomeLabel);

        // ✅ Stats panel
        javax.swing.JPanel statsPanel = new javax.swing.JPanel();
        statsPanel.setLayout(new java.awt.GridLayout(2, 3, 15, 15));
        statsPanel.setBackground(new java.awt.Color(51, 255, 51));
        statsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        statsPanel.setBounds(10, 55, 600, 340);

        statsPanel.add(createCard("MY TRANSACTIONS", myTransactions, new java.awt.Color(0, 153, 0)));
        statsPanel.add(createCard("BORROWED", myBorrowed, new java.awt.Color(0, 102, 0)));
        statsPanel.add(createCard("RETURNED", myReturned, new java.awt.Color(0, 153, 51)));
        statsPanel.add(createCard("TOTAL BOOKS", totalBooks, new java.awt.Color(0, 153, 0)));
        statsPanel.add(createCard("AVAILABLE BOOKS", availableBooks, new java.awt.Color(0, 102, 0)));

        jPanel1.setLayout(null);
        jPanel1.add(statsPanel);
        jPanel1.revalidate();
        jPanel1.repaint();

    } catch (Exception e) {
        System.out.println("User dashboard error: " + e.getMessage());
    }
}

private int getCount(java.sql.Connection conn, String sql) {
    try {
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();
        if (rs.next()) return rs.getInt(1);
    } catch (Exception e) {
        System.out.println("Count error: " + e.getMessage());
    }
    return 0;
}

private javax.swing.JPanel createCard(String title, int count, java.awt.Color color) {
    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setBackground(color);
    card.setLayout(new java.awt.BorderLayout());
    card.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK, 2));

    javax.swing.JLabel titleLabel = new javax.swing.JLabel(title, javax.swing.SwingConstants.CENTER);
    titleLabel.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 11));
    titleLabel.setForeground(java.awt.Color.WHITE);

    javax.swing.JLabel countLabel = new javax.swing.JLabel(String.valueOf(count), javax.swing.SwingConstants.CENTER);
    countLabel.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 36));
    countLabel.setForeground(java.awt.Color.WHITE);

    card.add(titleLabel, java.awt.BorderLayout.NORTH);
    card.add(countLabel, java.awt.BorderLayout.CENTER);

    return card;
}
    
    Color navcolor = new Color (0,153,0);
    Color headercolor = new Color (0,204,0);
    Color bodycolor = new Color (0,255,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        dashpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usertransactionpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bookspanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        accountpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        userbooks = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setLayout(null);

        navbar.setBackground(new java.awt.Color(0, 153, 0));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashpanel.setBackground(new java.awt.Color(0, 153, 0));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpanelMouseExited(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        dashpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 50));

        usertransactionpanel.setBackground(new java.awt.Color(0, 153, 0));
        usertransactionpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertransactionpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usertransactionpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usertransactionpanelMouseExited(evt);
            }
        });
        usertransactionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BORROW TRANSACTION");
        usertransactionpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        bookspanel.setBackground(new java.awt.Color(0, 153, 0));
        bookspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookspanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookspanelMouseExited(evt);
            }
        });
        bookspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BOOKS");
        bookspanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        usertransactionpanel.add(bookspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 50));

        navbar.add(usertransactionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 50));

        accountpanel.setBackground(new java.awt.Color(0, 153, 0));
        accountpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountpanelMouseExited(evt);
            }
        });
        accountpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACCOUNT");
        accountpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(accountpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 50));

        userbooks.setBackground(new java.awt.Color(0, 153, 0));
        userbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userbooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userbooksMouseExited(evt);
            }
        });
        userbooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BOOKS");
        userbooks.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        navbar.add(userbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-library-building-100 (1).png"))); // NOI18N
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 120));

        jPanel2.add(navbar);
        navbar.setBounds(0, 0, 230, 460);

        header.setBackground(new java.awt.Color(0, 204, 0));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USER DASHBOARD");
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 590, 40));

        jPanel2.add(header);
        header.setBounds(230, 0, 620, 60);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(230, 60, 590, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseEntered
        dashpanel.setBackground(bodycolor);
    }//GEN-LAST:event_dashpanelMouseEntered

    private void dashpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseExited
        dashpanel.setBackground(navcolor);
    }//GEN-LAST:event_dashpanelMouseExited

    private void usertransactionpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertransactionpanelMouseEntered
         usertransactionpanel.setBackground(bodycolor);
    }//GEN-LAST:event_usertransactionpanelMouseEntered

    private void usertransactionpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertransactionpanelMouseExited
        usertransactionpanel.setBackground(navcolor);
    }//GEN-LAST:event_usertransactionpanelMouseExited

    private void accountpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpanelMouseEntered
        accountpanel.setBackground(bodycolor);
    }//GEN-LAST:event_accountpanelMouseEntered

    private void accountpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpanelMouseExited
       accountpanel.setBackground(navcolor);
    }//GEN-LAST:event_accountpanelMouseExited

    private void accountpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpanelMouseClicked
       userForm us = new userForm();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountpanelMouseClicked

    private void usertransactionpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertransactionpanelMouseClicked
       usertransaction trans = new usertransaction();
       trans.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_usertransactionpanelMouseClicked

    private void bookspanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseEntered
       
    }//GEN-LAST:event_bookspanelMouseEntered

    private void bookspanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseExited

    }//GEN-LAST:event_bookspanelMouseExited

    private void userbooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbooksMouseEntered
        userbooks.setBackground(bodycolor);
    }//GEN-LAST:event_userbooksMouseEntered

    private void userbooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbooksMouseExited
       userbooks.setBackground(navcolor);
    }//GEN-LAST:event_userbooksMouseExited

    private void userbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbooksMouseClicked
       userbooks boks = new userbooks();
       boks.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_userbooksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountpanel;
    private javax.swing.JPanel bookspanel;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel userbooks;
    private javax.swing.JPanel usertransactionpanel;
    // End of variables declaration//GEN-END:variables
}
